///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/song.aks
/// Generation time: Wed Oct 26 01:30:44 CEST 2016
///

/// Song 'g_song' metadata macros
#define g_song_address  0x0200
#define g_song_size     145
#define g_song_end      0x291

/// Song 'g_song' array declaration
extern void g_song[g_song_size];
