///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/song.aks
<<<<<<< HEAD
/// Generation time: mié oct 26 19:26:35 CEST 2016
=======
/// Generation time: Wed Oct 26 19:08:13 CEST 2016
>>>>>>> e63f566c55e5740662b09f0adde28e2e1ef731d5
///

/// Song 'g_song' metadata macros
#define g_song_address  0x0200
#define g_song_size     145
#define g_song_end      0x291

/// Song 'g_song' array declaration
extern void g_song[g_song_size];
