///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/song.aks
/// Generation time: dom oct 23 18:23:41 CEST 2016
///

/// Song 'g_song' metadata macros
#define g_song_address  0x3000
#define g_song_size     145
#define g_song_end      0x3091

/// Song 'g_song' array declaration
extern void g_song[g_song_size];
